server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie
  output:
    ansi:
      enabled: always

###############
### LOGGING ###
###############
logging:                                                      # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework.web: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.commons.util.InetUtils: TRACE   # 开启这边的日志，可以打印出Spring查找网卡的过程

eureka:
  client:
    serviceUrl:
      defaultZone: http://mifan:Mifan2017!@peer1:8761/eureka/,http://mifan:Mifan2017!@peer2:8762/eureka/
  instance:
    prefer-ip-address: true

# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: true

# To set thread isolation to SEMAPHORE
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE