spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本     # 指定数据源类型
    data: classpath:data.sql            # 指定h2数据库的数据脚本
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  output:
    ansi:
      enabled: always

logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    org.springframework.cloud.commons.util.InetUtils: INFO   # 开启这边的日志，可以打印出Spring查找网卡的过程
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://mifan:Mifan2017!@peer1:8761/eureka/,http://mifan:Mifan2017!@peer2:8762/eureka/
    healthcheck:
      enabled: true

---
spring:
  profiles: a
server:
  port: 8081

---
spring:
  profiles: b
server:
  port: 8082

