########################################################
### EMBEDDED SERVER CONFIGURATION (ServerProperties) ###
########################################################
server:
  port: 8887
  session:
    timeout: 28800

##############
### SPRING ###
##############
spring:
  application:
    name: micro-service-config-server
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/helldzl/spring-cloud-config-repo
          username:
          password:
          clone-on-start: false
          search-paths: '{application}'
        health:
          repositories:
            myservice:
              label: master
              name: aa
  rabbitmq:
    host: 192.168.1.138
    port: 5672
    username: rabbitmq
    password: rabbitmq
  output:
    ansi:
      enabled: always

###########################
### SECURITY PROPERTIES ###
###########################
security:
  basic:
    enabled: true
  user:
    name: mifan
    password: Mifan2017!

###############
### LOGGING ###
###############
logging:
  level:
    root: INFO
    org.springframework.cloud: INFO
    org.springframework.boot: INFO

##############
### EUREKA ###
##############
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://mifan:Mifan2017!@${eureka.instance.hostname}:${server.port}/eureka/