server:
  port: 8090

spring:
  application:
    name: microservice-gateway-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://mifan:Mifan2017!@peer1:8761/eureka/,http://mifan:Mifan2017!@peer2:8762/eureka/
  instance:
    prefer-ip-address: true